import { CATEGORY_PRESENTATION } from '../classification/mail-classifier';
import type { MailCategory, MailboxAnalysisSummary, SenderStream } from '../../shared/contracts/analysis';

export interface PortableMailRule {
  id: string;
  senderDomain: string;
  receivingAddress: string | null;
  category: MailCategory;
  targetFolder: string;
  markRead: boolean;
  spam: boolean;
  confidence: number;
  observedMessages: number;
}

export interface PortableRulePack {
  format: 'sift-rule-pack';
  version: 1;
  generatedAt: string;
  classifierVersion: string;
  rules: PortableMailRule[];
  skippedAmbiguousStreams: number;
}

const excluded = new Set<MailCategory>(['personal', 'suspicious', 'other']);
const minimumConfidence = (category: MailCategory): number => category === 'spam' ? 0.94 : 0.82;
const sieveEscape = (value: string): string => value.replace(/\\/g, '\\\\').replace(/"/g, '\\"');

interface StreamGroup {
  address: string;
  domain: string;
  streams: SenderStream[];
}

export const buildPortableRulePack = (analysis: MailboxAnalysisSummary): PortableRulePack => {
  const grouped = new Map<string, StreamGroup>();
  for (const stream of analysis.topStreams) {
    if (stream.senderDomain === 'unknown-sender') continue;
    const key = `${stream.senderDomain}\0${stream.receivingAddress}`;
    const group = grouped.get(key) ?? { address: stream.receivingAddress, domain: stream.senderDomain, streams: [] };
    group.streams.push(stream);
    grouped.set(key, group);
  }

  let skippedAmbiguousStreams = 0;
  const rules: PortableMailRule[] = [];
  for (const group of grouped.values()) {
    const ordered = [...group.streams].sort((left, right) => right.messageCount - left.messageCount);
    const dominant = ordered[0]!;
    const total = ordered.reduce((sum, stream) => sum + stream.messageCount, 0);
    const dominance = dominant.messageCount / total;
    if (dominance < 0.75 || dominant.confidence < minimumConfidence(dominant.category) || excluded.has(dominant.category)) {
      skippedAmbiguousStreams += 1;
      continue;
    }
    const spam = dominant.category === 'spam';
    rules.push({
      id: `${group.domain}:${group.address}:${dominant.category}`,
      senderDomain: group.domain,
      receivingAddress: group.address === 'unknown' ? null : group.address,
      category: dominant.category,
      targetFolder: spam ? 'Spam' : CATEGORY_PRESENTATION[dominant.category].folder,
      markRead: dominant.category !== 'security' && !spam,
      spam,
      confidence: dominant.confidence,
      observedMessages: dominant.messageCount,
    });
  }
  rules.sort((left, right) => left.targetFolder.localeCompare(right.targetFolder) || left.senderDomain.localeCompare(right.senderDomain));
  return {
    format: 'sift-rule-pack',
    version: 1,
    generatedAt: analysis.analyzedAt,
    classifierVersion: analysis.classifierVersion,
    rules,
    skippedAmbiguousStreams,
  };
};

export const renderProtonSieve = (pack: PortableRulePack): string => {
  const lines = [
    'require ["fileinto", "imap4flags"];',
    '',
    '# Generated by Sift from locally classified sender streams.',
    '# Review before importing in Proton Mail Settings > Filters > Sieve.',
    '# Security alerts remain unread. Ambiguous and suspicious streams are omitted.',
    '',
  ];
  for (const rule of pack.rules) {
    const conditions = [`address :domain :is "from" "${sieveEscape(rule.senderDomain)}"`];
    if (rule.receivingAddress) conditions.push(`address :is ["delivered-to", "x-original-to"] "${sieveEscape(rule.receivingAddress)}"`);
    lines.push(`# ${rule.category} · ${rule.observedMessages} observed · ${Math.round(rule.confidence * 100)}% confidence`);
    lines.push(conditions.length === 1 ? `if ${conditions[0]} {` : `if allof (${conditions.join(', ')}) {`);
    if (rule.markRead) lines.push('  addflag "\\\\Seen";');
    lines.push(`  fileinto "${sieveEscape(rule.targetFolder)}";`);
    lines.push('  stop;', '}', '');
  }
  return `${lines.join('\n').trimEnd()}\n`;
};
