import type BetterSqlite3 from 'better-sqlite3';
import { createHash, randomUUID } from 'node:crypto';
import { buildPortableRulePack } from '../../core/rules/rule-pack';
import type { GmailOrganizationPlan } from '../../shared/contracts/gmail-organize';
import { gmailOrganizationPlanSchema } from '../../shared/contracts/gmail-organize';
import type { GmailConnectionSummary } from '../../shared/contracts/gmail';
import type { GmailAnalysisService } from './gmail-analysis-service';

export class GmailOrganizationRepository {
  readonly #database: BetterSqlite3.Database; readonly #analysis: GmailAnalysisService; readonly #profileId:string; readonly #now:()=>string; readonly #createId:()=>string;
  constructor(database:BetterSqlite3.Database, analysis:GmailAnalysisService, profileId:string, options:{now?:()=>string;createId?:()=>string}={}) { this.#database=database;this.#analysis=analysis;this.#profileId=profileId;this.#now=options.now??(()=>new Date().toISOString());this.#createId=options.createId??randomUUID; }
  generate(connection:GmailConnectionSummary):GmailOrganizationPlan {
    const summary=this.#analysis.get(connection); if(!summary) throw new Error('gmail_analysis_required'); const pack=buildPortableRulePack(summary);
    const analysisRow=this.#database.prepare('SELECT id FROM gmail_mailbox_analyses WHERE connection_id=? AND profile_id=?').get(connection.id,this.#profileId) as {id:string};
    const rules=pack.rules.map((rule)=>({ ...rule, existingMessages:(this.#database.prepare('SELECT COUNT(*) count FROM gmail_message_classifications WHERE analysis_id=? AND sender_domain=? AND category=?').get(analysisRow.id,rule.senderDomain,rule.category) as {count:number}).count, archive:rule.category!=='security' }));
    const revision=createHash('sha256').update(JSON.stringify(rules)).digest('hex'); const id=this.#createId(); const now=this.#now();
    this.#database.transaction(()=>{ this.#database.prepare('DELETE FROM gmail_organization_plans WHERE connection_id=?').run(connection.id); this.#database.prepare("INSERT INTO gmail_organization_plans(id,connection_id,analysis_id,revision,state,skipped_ambiguous_streams,created_at) VALUES (?,?,?,?,'draft',?,?)").run(id,connection.id,analysisRow.id,revision,pack.skippedAmbiguousStreams,now); const add=this.#database.prepare("INSERT INTO gmail_rule_actions(id,plan_id,rule_key,sender_domain,receiving_address,category,target_label,mark_read,archive,spam,confidence,existing_messages,state,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?, 'pending',?)"); for(const rule of rules) add.run(this.#createId(),id,rule.id,rule.senderDomain,rule.receivingAddress,rule.category,rule.targetFolder,rule.markRead?1:0,rule.archive?1:0,rule.spam?1:0,rule.confidence,rule.existingMessages,now); })(); return this.get(connection.id)!;
  }
  get(connectionId:string):GmailOrganizationPlan|null { const plan=this.#database.prepare('SELECT * FROM gmail_organization_plans WHERE connection_id=? ORDER BY rowid DESC LIMIT 1').get(connectionId) as Record<string,unknown>|undefined; if(!plan)return null; const rules=this.#database.prepare('SELECT * FROM gmail_rule_actions WHERE plan_id=? ORDER BY existing_messages DESC,target_label,sender_domain').all(plan.id) as Array<Record<string,unknown>>; return gmailOrganizationPlanSchema.parse({id:plan.id,revision:plan.revision,state:plan.state,ruleCount:rules.length,existingMessageCount:rules.reduce((sum,row)=>sum+Number(row.existing_messages),0),skippedAmbiguousStreams:plan.skipped_ambiguous_streams,rules:rules.map((row)=>({id:row.id,senderDomain:row.sender_domain,receivingAddress:row.receiving_address,category:row.category,targetLabel:row.target_label,markRead:Boolean(row.mark_read),archive:Boolean(row.archive),spam:Boolean(row.spam),existingMessages:row.existing_messages,confidence:row.confidence,state:row.state})),createdAt:plan.created_at,approvedAt:plan.approved_at}); }
  approve(connectionId:string,planId:string,revision:string):void { const result=this.#database.prepare("UPDATE gmail_organization_plans SET state='approved',approved_at=COALESCE(approved_at,?) WHERE id=? AND connection_id=? AND revision=? AND state IN ('draft','failed')").run(this.#now(),planId,connectionId,revision); if(!result.changes)throw new Error('gmail_plan_stale'); }
  recoverInterrupted(connectionId:string):void { const plan=this.#database.prepare("SELECT id FROM gmail_organization_plans WHERE connection_id=? AND state='running'").get(connectionId) as {id:string}|undefined;if(!plan)return;this.#database.transaction(()=>{this.#database.prepare("UPDATE gmail_organization_plans SET state='failed' WHERE id=?").run(plan.id);this.#database.prepare("UPDATE gmail_rule_actions SET state='failed',error_code='interrupted',updated_at=? WHERE plan_id=? AND state='running'").run(this.#now(),plan.id);})(); }
  planRow(planId:string):{connection_id:string;analysis_id:string}|null{return (this.#database.prepare('SELECT connection_id,analysis_id FROM gmail_organization_plans WHERE id=?').get(planId) as {connection_id:string;analysis_id:string}|undefined)??null;}
  setPlan(planId:string,state:'running'|'completed'|'failed'):void{this.#database.prepare('UPDATE gmail_organization_plans SET state=? WHERE id=?').run(state,planId);}
  setRule(ruleId:string,state:'running'|'succeeded'|'failed',filterId?:string,error?:string):void{this.#database.prepare('UPDATE gmail_rule_actions SET state=?,filter_id=COALESCE(?,filter_id),error_code=?,updated_at=? WHERE id=?').run(state,filterId??null,error??null,this.#now(),ruleId);}
  pending(planId:string):Array<{id:string;sender_domain:string;receiving_address:string|null;category:string;target_label:string;mark_read:number;archive:number;spam:number}>{return this.#database.prepare("SELECT * FROM gmail_rule_actions WHERE plan_id=? AND state IN ('pending','failed') ORDER BY rowid").all(planId) as never;}
  messageIds(analysisId:string,domain:string,category:string):string[]{return (this.#database.prepare('SELECT gim.gmail_message_id FROM gmail_message_classifications gmc JOIN gmail_indexed_messages gim ON gim.id=gmc.message_row_id WHERE gmc.analysis_id=? AND gmc.sender_domain=? AND gmc.category=?').all(analysisId,domain,category) as Array<{gmail_message_id:string}>).map((row)=>row.gmail_message_id);}
}
