import type { OAuthFetch } from './gmail-oauth';
import { refreshGmailAccessToken } from './gmail-oauth';
import type { GmailConnectionRepository } from './gmail-connection-repository';
import type { GmailOrganizationRepository } from './gmail-organization-repository';

const api=async(fetchPort:OAuthFetch,token:string,url:string,init:RequestInit={})=>{const response=await fetchPort(url,{...init,headers:{authorization:`Bearer ${token}`,'content-type':'application/json',...(init.headers??{})}});if(!response.ok)throw new Error(`gmail_api_${response.status}`);return response.status===204?null:await response.json();};
export class GmailOrganizationRunner { constructor(readonly connections:GmailConnectionRepository,readonly plans:GmailOrganizationRepository,readonly fetchPort:OAuthFetch=fetch){}
  async run(planId:string):Promise<void>{const credentials=this.connections.credentials();if(!credentials)throw new Error('gmail_not_connected');const plan=this.plans.planRow(planId);if(!plan||plan.connection_id!==credentials.connection.id)throw new Error('gmail_plan_missing');this.plans.setPlan(planId,'running');try{const token=await refreshGmailAccessToken(credentials.connection.clientId,credentials.refreshToken,credentials.clientSecret,this.fetchPort);const labelPayload=await api(this.fetchPort,token,'https://gmail.googleapis.com/gmail/v1/users/me/labels') as {labels?:Array<{id:string;name:string}>};const labels=new Map((labelPayload.labels??[]).map((label)=>[label.name,label.id]));const filterPayload=await api(this.fetchPort,token,'https://gmail.googleapis.com/gmail/v1/users/me/settings/filters') as {filter?:unknown[]};void filterPayload;for(const rule of this.plans.pending(planId)){this.plans.setRule(rule.id,'running');try{let labelId='SPAM';if(!rule.spam){labelId=labels.get(rule.target_label)??'';if(!labelId){const created=await api(this.fetchPort,token,'https://gmail.googleapis.com/gmail/v1/users/me/labels',{method:'POST',body:JSON.stringify({name:rule.target_label,labelListVisibility:'labelShow',messageListVisibility:'show'})}) as {id:string};labelId=created.id;labels.set(rule.target_label,labelId);}}const removeLabelIds=[...(rule.archive?['INBOX']:[]),...(rule.mark_read?['UNREAD']:[])];const criteria={from:`@${rule.sender_domain}`,...(rule.receiving_address?{to:rule.receiving_address}:{})};const action={addLabelIds:[labelId],removeLabelIds};const created=await api(this.fetchPort,token,'https://gmail.googleapis.com/gmail/v1/users/me/settings/filters',{method:'POST',body:JSON.stringify({criteria,action})}) as {id:string};const ids=this.plans.messageIds(plan.analysis_id,rule.sender_domain,rule.category);for(let offset=0;offset<ids.length;offset+=1000)await api(this.fetchPort,token,'https://gmail.googleapis.com/gmail/v1/users/me/messages/batchModify',{method:'POST',body:JSON.stringify({ids:ids.slice(offset,offset+1000),addLabelIds:[labelId],removeLabelIds})});this.plans.setRule(rule.id,'succeeded',created.id);}catch(error){this.plans.setRule(rule.id,'failed',undefined,error instanceof Error?error.message:'gmail_rule_failed');}}const failed=this.plans.pending(planId).length;this.plans.setPlan(planId,failed?'failed':'completed');}catch(error){this.plans.setPlan(planId,'failed');throw error;}}
}
